<script setup lang="ts">
const [container] = useKeenSlider(
  {
    loop: true,
    slides: {
      perView: 1,
      spacing: 15,
    },
  },
  [
    (slider) => {
      let timeout: ReturnType<typeof setTimeout>;
      let mouseOver = false;

      function clearNextTimeout() {
        clearTimeout(timeout);
      }

      function nextTimeout() {
        clearTimeout(timeout);

        if (mouseOver) return;

        timeout = setTimeout(() => {
          slider.next();
        }, 3000);
      }

      slider.on("created", () => {
        slider.container.addEventListener("mouseover", () => {
          mouseOver = true;
          clearNextTimeout();
        });

        slider.container.addEventListener("mouseout", () => {
          mouseOver = false;
          nextTimeout();
        });

        nextTimeout();
      });

      slider.on("dragStarted", clearNextTimeout);
      slider.on("animationEnded", nextTimeout);
      slider.on("updated", nextTimeout);
    },
  ],
);
</script>
<template>
  <div
    ref="container"
    class="keen-slider sm:!hidden slide-in-elliptic-top-fwd max-h-[700px]"
  >
    <div class="slider slider-one keen-slider__slide">
      <img
        alt="حلما شاپ"
        class="w-full h-full object-cover"
        src="/images/banner-one-small.webp"
        fetchpriority="high"
        height="500"
        width="500"
      />
    </div>
    <div class="slider slider-one keen-slider__slide">
      <img
        alt="حلما شاپ"
        class="w-full h-full object-cover"
        src="/images/banner-four-small.webp"
        fetchpriority="high"
        height="500"
        width="500"
      />
    </div>
    <div class="slider keen-slider__slide">
      <img
        class="w-full h-full object-cover"
        src="/images/banner-three-small.webp"
        alt="سوهان و گز حلما وفایی"
        fetchpriority="high"
        width="500"
        height="500"
      />
    </div>
    <div class="slider keen-slider__slide">
      <img
        class="w-full h-full object-cover"
        src="/images/banner-two-small.webp"
        alt="سوهان و گز حلما وفایی"
        fetchpriority="high"
        width="500"
        height="500"
      />
    </div>
  </div>
</template>
<style>
.slider {
  @apply relative w-full rounded-lg overflow-hidden aspect-[1/1];
}

.slider-one__content {
  @apply absolute  z-10 left-[15vw] top-[26vw] flex flex-col gap-7 items-center;
}

.slider-one__content p:nth-child(1) {
  @apply text-2xl font-bold text-[var(--gold-two)];
}

.slider-one__content p:nth-child(2) {
  @apply text-base font-bold text-white max-w-[35vw] text-center text-wrap;
}

.slider-one__content p:nth-child(3) {
  @apply text-[0.70rem]  font-bold text-[var(--gold-two)]  text-center text-wrap;
}

.slider-two__content {
  @apply absolute  z-10  top-[38vw] flex flex-col gap-2 items-start;
}

.slider-two > p:nth-of-type(1) {
  @apply text-2xl top-[10vw] absolute right-0 left-0 m-auto text-center font-bold text-[var(--gold-two)];
}
.slider-two > p:nth-of-type(2) {
  @apply text-[0.60rem]  top-[41vw] absolute right-[9vw] text-justify max-w-[30vw] text-wrap font-bold text-white;
}
.slider-two > p:nth-of-type(3) {
  @apply text-sm top-[80vw] absolute right-0 left-0 m-auto text-center font-bold text-[var(--gold-two)];
}
.slide-in-elliptic-top-fwd {
  -webkit-animation: slide-in-elliptic-top-fwd 2s
    cubic-bezier(0.25, 0.46, 0.45, 0.94) 2s both;
  animation: slide-in-elliptic-top-fwd 2s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2026-7-1 14:50:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
    transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
    transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
    transform-origin: 50% 1400px;
    opacity: 1;
  }
}
@keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
    transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
    transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
    transform-origin: 50% 1400px;
    opacity: 1;
  }
}
</style>
