<script setup lang="ts">
import { useKeenSlider } from "keen-slider/vue.es";
const [container, slider] = useKeenSlider(
  {
    loop: true,
    slides: {
      perView: 1,
      spacing: 15,
    },
  },
  [
    (slider) => {
      let timeout: ReturnType<typeof setTimeout>;
      let mouseOver = false;

      function clearNextTimeout() {
        clearTimeout(timeout);
      }

      function nextTimeout() {
        clearTimeout(timeout);

        if (mouseOver) return;

        timeout = setTimeout(() => {
          slider.next();
        }, 3000);
      }

      slider.on("created", () => {
        slider.container.addEventListener("mouseover", () => {
          mouseOver = true;
          clearNextTimeout();
        });

        slider.container.addEventListener("mouseout", () => {
          mouseOver = false;
          nextTimeout();
        });

        nextTimeout();
      });

      slider.on("dragStarted", clearNextTimeout);
      slider.on("animationEnded", nextTimeout);
      slider.on("updated", nextTimeout);
    },
  ],
);

onMounted(() => {
  if (!container.value) return;

  const observer = new ResizeObserver(() => {
    slider.value?.update();
  });

  observer.observe(container.value);

  onBeforeUnmount(() => {
    observer.disconnect();
  });
});
</script>
<template>
  <div
    ref="container"
    class="keen-slider slide-in-elliptic-top-fwd sm:!hidden  max-h-[700px] min-h-[100vw]"
  >
    <div class="keen-slider__slide">
      <img
        alt="حلما شاپ"
        class="w-full h-full object-cover"
        src="/images/banner-one-small.webp"
        fetchpriority="high"
        @load="slider?.update()"
        height="500"
        width="500"
      />
    </div>
    <div class="keen-slider__slide">
      <img
        alt="حلما شاپ"
        class="w-full h-full object-cover"
        src="/images/banner-four-small.webp"
        fetchpriority="high"
        height="500"
        width="500"
      />
    </div>
    <div class="keen-slider__slide">
      <img
        class="w-full h-full object-cover"
        src="/images/banner-three-small.webp"
        alt="سوهان و گز حلما وفایی"
        fetchpriority="high"
        width="500"
        height="500"
      />
    </div>
    <div class="keen-slider__slide">
      <img
        class="w-full h-full object-cover"
        src="/images/banner-two-small.webp"
        alt="سوهان و گز حلما وفایی"
        fetchpriority="high"
        width="500"
        height="500"
      />
    </div>
  </div>
</template>
<style>
.keen-slider__slide {
  @apply rounded-lg overflow-hidden ;
}

.slide-in-elliptic-top-fwd {
  -webkit-animation: slide-in-elliptic-top-fwd 2s
    cubic-bezier(0.25, 0.46, 0.45, 0.94) 2s both;
  animation: slide-in-elliptic-top-fwd 2s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2026-7-1 14:50:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
    transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
    transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
    transform-origin: 50% 1400px;
    opacity: 1;
  }
}
@keyframes slide-in-elliptic-top-fwd {
  0% {
    -webkit-transform: translateY(-600px) rotateX(-30deg) scale(0);
    transform: translateY(-600px) rotateX(-30deg) scale(0);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotateX(0) scale(1);
    transform: translateY(0) rotateX(0) scale(1);
    -webkit-transform-origin: 50% 1400px;
    transform-origin: 50% 1400px;
    opacity: 1;
  }
}
</style>
