name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt
        run: npm run build

      - name: Debug files
        run: |
          echo "Current directory:"
          pwd

          echo "Root files:"
          ls -la

          echo ".output exists?"
          ls -la .output || true

          echo "Find output:"
          find . -maxdepth 3

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          overwrite: true
          source: ".output/**,package.json,package-lock.json"
          target: "/root/app/frontend"

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd /root/app
            docker-compose build frontend
            docker-compose up -d frontend